---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.11.18'
  data_bags_path: 'test/fixtures/data_bags'
  roles_path: 'test/fixtures/roles'

platforms:
  - name: ubuntu-14.04
    box: 'bento/ubuntu-14.04'

  - name: centos-7.2
    box: 'bento/centos-7.2'

suites:
  - name: user_management
    run_list:
      - recipe[didata-unix::users]
    attributes:
    excludes:
      - win2008
      - win2012

  - name: package_management
    run_list:
      - recipe[didata-unix::packages]
    attributes:
    excludes:
      - win2008
      - win2012